package wasmcloud:postgresql;

interface types {
    record row {
        field-name: string,
        value: data-type,
    }
    
    variant data-type {
        int32(s32),
        int64(s64),
        uint32(u32),
        uint64(u64),
        float(float64),
        double(float64),
        str(string),
        boolean(bool),
        date(string),
        time(string),
        timestamp(string),
        binary(list<u8>),
        null
    }
}

interface readwrite {
    use types.{row};
    
    query: func(query: string, params: list<string>) -> result<list<row>, string>;
    
    exec: func(query: string, params: list<string>) -> result<u32, string>;
}